{{- if .Values.ethereum.password.enabled -}}
---
apiVersion: v1
data:
  password: {{ .Values.ethereum.password.value }}
  {{ (.Files.Glob "secrets/UTC*").AsSecrets }}
kind: Secret
metadata:
  name: ethereum-password
  namespace: ethereum
  labels:
    {{- include "ethereum.labels" . | nindent 4 }}
    app.kubernetes.io/component: login
{{- end }}
