apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    {{- include "ethereum.labels" . | nindent 4 }}
spec:
  externalIPs:
    {{ .Values.service.externalIPs }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.auth.port }}
      targetPort: {{ .Values.service.auth.targetPort }}
      protocol: TCP
      name: {{ .Values.service.auth.name }}
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
      name: {{ .Values.service.http.name }}
    - port: {{ .Values.service.node.port }}
      targetPort: {{ .Values.service.node.targetPort }}
      protocol: TCP
      name: {{ .Values.service.node.name }}
    - port: {{ .Values.service.wshost.port }}
      targetPort: {{ .Values.service.wshost.targetPort }}
      protocol: TCP
      name: {{ .Values.service.wshost.name }}
  selector:
    {{- include "ethereum.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
